name: OCI Auto Instance Creator
on:
  schedule:
    - cron: '*/10 * * * *' # Triggers every 10 minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    # We set a 10-minute timeout so the next scheduled run doesn't overlap
    timeout-minutes: 10 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create API Key File
        run: |
          echo "${{ secrets.OCI_KEY_FILE }}" > oci.key
          chmod 600 oci.key

      - name: Run Script
        env:
          # --- YOUR CONFIG SECRETS ---
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_IMAGE_ID: ${{ secrets.IMAGE_ID }}
          OCI_SUBNET_ID: ${{ secrets.SUBNET_ID }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          CPUS: ${{ secrets.CPUS }}
          VOLUME_SIZE: ${{ secrets.VOLUME_SIZE }}
          KEY_PATH: ./oci.key

          # --- THE LIMITING LOGIC ---
          # This tells the Go code to stop after 6 attempts
          MAX_ATTEMPTS: 5
          # This ensures it waits 60 seconds between those 6 attempts
          CREATE_INTERVAL_SECONDS: 60 

        run: |
          go build -o creator *.go
          ./creator